# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki
#
# To get this particular package to run, I used the rJava example 
# (rJava is a dependency of the ReporteRs package)
# https://github.com/csgillespie/travis-examples/tree/rjava

language: java

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  
install:
  - sudo R CMD javareconf
  - ./travis-tool.sh install_github davidgohel/ReporteRsjars
  - ./travis-tool.sh install_github davidgohel/ReporteRs
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package jimhester/covr

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'covr::coveralls()'
  
notifications:
  email:
    on_success: change
    on_failure: change